<?php

return [
    'default' => env('DEFAULT_UNIVERSITY_CODE', 'LASU'),

    /*
    |--------------------------------------------------------------------------
    | LASU Academic Structure
    |--------------------------------------------------------------------------
    | Structured academic units for Lagos State University, sourced from the
    | official faculties, schools, and directorates listed on lasu.edu.ng.
    | Each faculty contains its constituent departments. Free-text department
    | fields across the application should use this config as a data-driven
    | dropdown source instead.
    |
    */

    'faculties' => [
        'art' => [
            'name' => 'Faculty of Arts',
            'code' => 'ART',
            'departments' => [
                'english' => 'Department of English',
                'foreign_languages' => 'Department of Foreign Languages',
                'philosophy' => 'Department of Philosophy',
                'history' => 'Department of History & Strategic Studies',
                'theatre_arts' => 'Department of Theatre Arts',
                'music' => 'Department of Music',
                'visual_arts' => 'Department of Visual and Creative Arts',
                'mass_communication' => 'Department of Mass Communication',
                'cinema' => 'Department of Cinema',
                'linguistics' => 'Department of Linguistics and Nigerian Languages',
            ],
        ],
        'science' => [
            'name' => 'Faculty of Science',
            'code' => 'SCI',
            'departments' => [
                'biology' => 'Department of Biology',
                'chemistry' => 'Department of Chemistry',
                'physics' => 'Department of Physics',
                'mathematics' => 'Department of Mathematics',
                'statistics' => 'Department of Statistics',
                'computer_science' => 'Department of Computer Science',
                'microbiology' => 'Department of Microbiology',
                'biochemistry' => 'Department of Biochemistry',
                'botany' => 'Department of Botany',
                'zoology' => 'Department of Zoology',
                'geology' => 'Department of Geology',
                'meteorology' => 'Department of Meteorology',
                'physics_it' => 'Department of Physics (Industrial Technology)',
            ],
        ],
        'engineering' => [
            'name' => 'Faculty of Engineering',
            'code' => 'ENG',
            'departments' => [
                'civil' => 'Department of Civil & Environmental Engineering',
                'mechanical' => 'Department of Mechanical Engineering',
                'electrical_electronics' => 'Department of Electronic & Electrical Engineering',
                'computer_engineering' => 'Department of Computer Engineering',
                'chemical_engineering' => 'Department of Chemical Engineering',
                'industrial' => 'Department of Industrial & Production Engineering',
                'materials' => 'Department of Materials & Metallurgical Engineering',
                'aerospace' => 'Department of Aerospace Engineering',
                'agricultural' => 'Department of Agricultural Engineering',
            ],
        ],
        'management_sciences' => [
            'name' => 'Faculty of Business & Management Sciences',
            'code' => 'MGT',
            'departments' => [
                'business' => 'Department of Business & Financial Management',
                'banking_finance' => 'Department of Banking & Finance',
                'marketing' => 'Department of Marketing',
                'human_resources' => 'Department of Human Resources & Industrial Relations',
                'transport' => 'Department of Transport & Logistics Management',
                'accounting' => 'Department of Accounting',
                'entrepreneurship' => 'Department of Entrepreneurship & Innovation',
                'public_administration' => 'Department of Public Administration & Policy',
            ],
        ],
        'social_sciences' => [
            'name' => 'Faculty of Social Sciences',
            'code' => 'SOC',
            'departments' => [
                'economics' => 'Department of Economics',
                'political_science' => 'Department of Political Science & International Relations',
                'sociology' => 'Department of Sociology',
                'psychology' => 'Department of Psychology',
                'geography' => 'Department of Geography',
                'history_intl_studies' => 'Department of History & International Studies',
                'library_studies' => 'Department of Library & Information Studies',
                'social_work' => 'Department of Social Work',
                'peace_studies' => 'Department of Peace & Conflict Studies',
                'development_studies' => 'Department of Development Studies',
            ],
        ],
        'environmental_sciences' => [
            'name' => 'Faculty of Environmental Sciences',
            'code' => 'ENV',
            'departments' => [
                'architecture' => 'Department of Architecture',
                'building' => 'Department of Building & Estate Management',
                'quantity_surveying' => 'Department of Quantity Surveying',
                'urban_planning' => 'Department of Urban & Regional Planning',
                'landscape_architecture' => 'Department of Landscape Architecture',
                'environmental_mgmt' => 'Department of Environmental Management',
                'geography_env' => 'Department of Geography & Environmental Science',
                'surveying_geoinformatics' => 'Department of Surveying & Geoinformatics',
            ],
        ],
        'law' => [
            'name' => 'Faculty of Law',
            'code' => 'LAW',
            'departments' => [
                'law' => 'Department of Law',
                'commercial_law' => 'Department of Commercial Law',
                'public_law' => 'Department of Public Law',
                'private_law' => 'Department of Private Law',
                'international_law' => 'Department of International Law',
                'juris_prudence' => 'Department of Jurisprudence & Legal Theory',
                'alternative_dispute' => 'Department of Alternative Dispute Resolution',
            ],
        ],
        'education' => [
            'name' => 'Faculty of Education',
            'code' => 'EDU',
            'departments' => [
                'curriculum_studies' => 'Department of Curriculum Studies & Instruction',
                'educational_admin' => 'Department of Educational Administration & Planning',
                'psychology' => 'Department of Educational Psychology',
                'english_ed' => 'Department of English Education',
                'mathematics_ed' => 'Department of Mathematics Education',
                'science_ed' => 'Department of Science Education',
                'social_studies_ed' => 'Department of Social Studies Education',
                'humanities_ed' => 'Department of Humanities Education',
                'technical_ed' => 'Department of Technical Education',
                'adult_education' => 'Department of Adult Education & Community Development',
                'library_education' => 'Department of Library & Information Science Education',
            ],
        ],
        'communications' => [
            'name' => 'Faculty of Communications',
            'code' => 'COM',
            'departments' => [
                'mass_communication' => 'Department of Mass Communication',
                'journalism' => 'Department of Journalism',
                'public_relations' => 'Department of Public Relations',
                'advertising' => 'Department of Advertising & Brand Communication',
                'film_studies' => 'Department of Film & Media Studies',
                'digital_media' => 'Department of Digital Media & Communication',
            ],
        ],
        'agriculture' => [
            'name' => 'Faculty of Agriculture',
            'code' => 'AGR',
            'departments' => [
                'crop' => 'Department of Crop, Soil & Environmental Sciences',
                'animal_science' => 'Department of Animal Science',
                'food_technology' => 'Department of Food & Industrial Technology',
                'agricultural_economics' => 'Department of Agricultural Economics & Extension',
                'agronomy' => 'Department of Agronomy',
                'animal_production' => 'Department of Animal Production',
                'soil_microbiology' => 'Department of Soil & Environmental Microbiology',
                'home_economics' => 'Department of Home Economics & Food Technology',
                'forestry' => 'Department of Forestry & Wildlife Management',
                'fisheries' => 'Department of Fisheries & Aquaculture',
            ],
        ],
    ],

    'schools_and_directorates' => [
        'basic_medical_sciences' => [
            'name' => 'College of Medicine (Basic Medical Sciences)',
            'code' => 'BMS',
            'type' => 'school',
            'departments' => [
                'anatomy' => 'Department of Anatomy',
                'physiology' => 'Department of Physiology',
                'biochemistry' => 'Department of Biochemistry',
                'histology' => 'Department of Histology',
                'chemical_pathology' => 'Department of Chemical Pathology',
                'medical_microbiology' => 'Department of Medical Microbiology & Immunology',
                'pharmacology' => 'Department of Pharmacology & Therapeutics',
                'community_health' => 'Department of Community Health & Primary Care',
                'mental_health' => 'Department of Mental Health & Psychiatry',
                'morbid_anatomy' => 'Department of Morbid Anatomy & Pathology',
            ],
        ],
        'clinical_sciences' => [
            'name' => 'College of Medicine (Clinical Sciences)',
            'code' => 'CLS',
            'type' => 'school',
            'departments' => [
                'medicine' => 'Department of Medicine',
                'surgery' => 'Department of Surgery',
                'obstetrics_gynaecology' => 'Department of Obstetrics & Gynaecology',
                'paediatrics' => 'Department of Paediatrics',
                'anaesthesia' => 'Department of Anaesthesia & Intensive Care',
                'orthopaedics' => 'Department of Orthopaedic & Trauma Surgery',
                'ophthalmology' => 'Department of Ophthalmology',
                'ent_surgery' => 'Department of ENT & Head/Neck Surgery',
                'radiology' => 'Department of Radiology',
                'internal_medicine' => 'Department of Internal Medicine',
                'community_medicine' => 'Department of Community Medicine',
                'emergency_medicine' => 'Department of Emergency Medicine',
                'paediatric_surgery' => 'Department of Paediatric Surgery',
                'neurosurgery' => 'Department of Neurosurgery',
            ],
        ],
        'dentistry' => [
            'name' => 'College of Dental Sciences',
            'code' => 'DEN',
            'type' => 'school',
            'departments' => [
                'dentistry' => 'Department of Dental Sciences',
                'oral_surgery' => 'Department of Oral & Maxillofacial Surgery',
                'endodontics' => 'Department of Endodontics',
                'periodontics' => 'Department of Periodontics',
                'orthodontics' => 'Department of Orthodontics',
                'prosthodontics' => 'Department of Prosthodontics',
                'pediatric_dentistry' => 'Department of Paediatric Dentistry',
                'dental_materials' => 'Department of Dental Materials & Pharmacology',
                'oral_pathology' => 'Department of Oral Pathology & Oral Biology',
                'community_dentistry' => 'Department of Community Dentistry',
            ],
        ],
        'allied_health' => [
            'name' => 'College of Allied Health Sciences',
            'code' => 'AHS',
            'type' => 'school',
            'departments' => [
                'medical_lab' => 'Department of Medical Laboratory Sciences',
                'radiography' => 'Department of Radiography',
                'physiotherapy' => 'Department of Physiotherapy',
                'optometry' => 'Department of Optometry',
                'pharmacy' => 'Department of Pharmacy',
                'nutrition' => 'Department of Nutrition & Dietetics',
                'audiology' => 'Department of Audiology & Speech-Language Pathology',
                'community_health_ahs' => 'Department of Community Health',
                'medical_imaging' => 'Department of Medical Imaging & Radiography',
                'clinical_chemistry' => 'Department of Clinical Chemistry',
                'hearing_science' => 'Department of Hearing Science',
                'prosthetics' => 'Department of Prosthetics & Orthotics',
            ],
        ],
        'computing' => [
            'name' => 'School of Information Technology & Computing',
            'code' => 'CIT',
            'type' => 'school',
            'departments' => [
                'computer_science' => 'Department of Computer Science',
                'information_technology' => 'Department of Information Technology',
                'software_engineering' => 'Department of Software Engineering',
                'cyber_security' => 'Department of Cybersecurity',
                'data_science' => 'Department of Data Science',
                'artificial_intelligence' => 'Department of Artificial Intelligence',
                'telecommunications' => 'Department of Telecommunications',
                'hci' => 'Department of Human-Computer Interaction',
                'database_systems' => 'Department of Database Systems',
                'networking' => 'Department of Computer Networking',
            ],
        ],
        'transport' => [
            'name' => 'Department of Transport Studies',
            'code' => 'TRN',
            'type' => 'directorate',
            'departments' => [
                'transport_studies' => 'Department of Transport Studies',
                'logistics' => 'Department of Logistics Management',
                'aviation_mgmt' => 'Department of Aviation Management',
                'maritime_studies' => 'Department of Maritime Studies',
            ],
        ],
        'library' => [
            'name' => 'Library & Information Technology',
            'code' => 'LIB',
            'type' => 'directorate',
            'departments' => [
                'library_studies' => 'Department of Library & Information Science',
                'information_archives' => 'Department of Information Studies & Archives',
                'bibliography' => 'Department of Bibliography & Scholarly Communication',
                'digital_preservation' => 'Department of Digital Preservation',
            ],
        ],
        'cessed' => [
            'name' => 'Centre for Academic & Educational Development (CESSED)',
            'code' => 'CES',
            'type' => 'directorate',
            'departments' => [
                'academic_development' => 'Department of Academic Development',
                'educational_dev' => 'Department of Educational Development & Quality Assurance',
                'research_dev' => 'Department of Research & Innovation Development',
                'teaching_learning' => 'Department of Teaching, Learning & Assessment',
                'curriculum_innovation' => 'Department of Curriculum Innovation & Pedagogy',
                'assessment_standards' => 'Department of Assessment & Academic Standards',
            ],
        ],
    ],
];
